
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace TicTacToeModel.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            TicTacToeModel.ModelInput sampleData = new TicTacToeModel.ModelInput()
            {
                PlayerValue = 1F,
                C0 = 1F,
                C1 = 2F,
                C2 = 2F,
                C3 = 2F,
                C4 = 1F,
                C5 = 1F,
                C6 = 0F,
                C7 = 1F,
                C8 = 2F,
            };

            Console.WriteLine("Using model to make single prediction -- Comparing actual Position with predicted Position from sample data...\n\n");


            Console.WriteLine($"PlayerValue: {1F}");
            Console.WriteLine($"C0: {1F}");
            Console.WriteLine($"C1: {2F}");
            Console.WriteLine($"C2: {2F}");
            Console.WriteLine($"C3: {2F}");
            Console.WriteLine($"C4: {1F}");
            Console.WriteLine($"C5: {1F}");
            Console.WriteLine($"C6: {0F}");
            Console.WriteLine($"C7: {1F}");
            Console.WriteLine($"C8: {2F}");
            Console.WriteLine($"Position: {6F}");


            var sortedScoresWithLabel = TicTacToeModel.PredictAllLabels(sampleData);
            Console.WriteLine($"{"Class",-40}{"Score",-20}");
            Console.WriteLine($"{"-----",-40}{"-----",-20}");

            foreach (var score in sortedScoresWithLabel)
            {
                Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
            }
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
